# Generated by Django 4.2.3 on 2023-07-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_cities_startdate_cities_updated_department_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
