# Generated by Django 4.2.3 on 2023-07-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs_settings', '0007_manager_alter_role_options_alter_role_role_name'),
        ('human_resource', '0004_remove_cities_country_remove_country_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=1250, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=1250, verbose_name='Last Name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.manager', verbose_name='Region')),
                ('sub_deparment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.subdepartment', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
