# Generated by Django 4.2.3 on 2023-07-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0006_employee_role_alter_employee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sub_deparment',
        ),
    ]
