# Generated by Django 4.2.3 on 2023-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0008_employee_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='', max_length=1250, verbose_name='Employees Name'),
        ),
    ]
