# Generated by Django 4.2.3 on 2023-07-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_settings', '0014_remove_manager_work_location_branchmanager_and_more'),
        ('human_resource', '0010_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.branchmanager', verbose_name='Manager'),
        ),
    ]
