# Generated by Django 4.2.3 on 2023-07-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Bar Code'),
        ),
    ]
