# Generated by Django 4.2.3 on 2023-07-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
