# Generated by Django 4.2.3 on 2023-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_storage_storage_code_alter_storage_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Storage Capacity(Sq M)'),
        ),
    ]
