# Generated by Django 4.2.3 on 2023-07-12 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_reorder_level'),
        ('inventory_management', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('inventory_id', models.CharField(blank=True, default=inventory_management.models.increment_inventory_number, max_length=500, null=True, verbose_name='Inventory Id')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('supervised_by', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Supervisor By')),
                ('storage_location', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.storage', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventory', verbose_name='Invoice Id')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
