# Generated by Django 4.2.3 on 2023-07-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_inventory_inventoryitems_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitems',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items Details'},
        ),
    ]
