# Generated by Django 4.2.3 on 2023-07-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_alter_inventoryitems_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='city',
        ),
    ]
