# Generated by Django 4.2.3 on 2023-07-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_alter_inventory_storage_location_delete_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventory', verbose_name='Inventory Id'),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='status',
            field=models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True),
        ),
    ]
