# Generated by Django 4.2.3 on 2023-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=100, null=True, verbose_name='Supplier Type')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=2550, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='City')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 1 +237')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone 2 +237')),
                ('email', models.EmailField(blank=True, help_text='e.g ag@gmail.com', max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='e.g www.google.com', null=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
