# Generated by Django 4.2.3 on 2023-07-13 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_reorder_level'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Date of Purchase')),
                ('invoice_id', models.CharField(blank=True, default=purchase.models.increment_invoice_number, help_text='Auto Generated', max_length=500, null=True, verbose_name='Purchase Invoice Id')),
                ('employee', models.CharField(default='', help_text='e.g Agbor Charles', max_length=200, verbose_name='Employee')),
                ('due_date', models.DateField(blank=True, help_text='e.g 2023-07-01', null=True, verbose_name='Due Date')),
                ('vendor', models.ForeignKey(blank=True, help_text='e.g Robertson Winery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoicesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Purchases', 'Purchases'), ('Return Outwards', 'Return Outwards')], default='Morning', max_length=500, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('total_at_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseinvoices', verbose_name='Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Purchase Invoices Items',
                'verbose_name_plural': 'Purchase Invoices Items',
            },
        ),
    ]
