# Generated by Django 4.2.3 on 2023-07-16 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_location', '0001_initial'),
        ('purchase', '0004_purchaseinvoices_storage_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoicesdetail',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='e.g WareHouse Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_location.storage', verbose_name='WareHouse'),
        ),
    ]
