# Generated by Django 4.2.3 on 2023-07-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseinvoicesdetail_storage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoicesdetail',
            name='storage_location',
        ),
    ]
