# Generated by Django 4.2.3 on 2023-07-19 03:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import returns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_reorder_level'),
        ('storage_location', '0001_initial'),
        ('customers', '0005_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Date of Purchase')),
                ('return_id', models.CharField(blank=True, default=returns.models.increment_invoice_number, help_text='Auto Generated', max_length=500, null=True, verbose_name='Purchase Invoice Id')),
                ('employee', models.CharField(default='', help_text='e.g Agbor Charles', max_length=200, verbose_name='Employee')),
                ('customer', models.ForeignKey(blank=True, help_text='e.g Robertson Winery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Supplier')),
                ('storage_location', models.ForeignKey(blank=True, help_text='e.g WareHouse Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_location.storage', verbose_name='WareHouse')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Quantity')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('total_at_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
                ('return_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.return', verbose_name='Purchase Invoice Id')),
            ],
            options={
                'verbose_name': 'Return  Items',
                'verbose_name_plural': 'Return  Items',
            },
        ),
    ]
