# Generated by Django 4.2.3 on 2023-07-19 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import returns.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_customer_type_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Date of Return'),
        ),
        migrations.AlterField(
            model_name='return',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='e.g santa lucia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_id',
            field=models.CharField(blank=True, default=returns.models.increment_invoice_number, help_text='Auto Generated', max_length=500, null=True, verbose_name='Return Invoice Id'),
        ),
    ]
