# Generated by Django 4.2.3 on 2023-07-08 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_settings', '0003_remove_role_department_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='configs_settings.subdepartment'),
        ),
    ]
