# Generated by Django 4.2.3 on 2023-07-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_settings', '0012_rename_workloacation_worklocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklocation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Active', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.cities', verbose_name='City'),
        ),
    ]
