# Generated by Django 4.2.3 on 2023-07-12 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_settings', '0016_remove_branchmanager_work_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='branch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.branchmanager', verbose_name='Branch Manager'),
        ),
    ]
