# Generated by Django 4.2.3 on 2023-07-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs_settings', '0017_alter_worklocation_branch_manager'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(default='', max_length=200, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='customer',
            name='quarter',
            field=models.CharField(blank=True, default='Kumba', max_length=100, null=True, verbose_name='Quarter'),
        ),
        migrations.AddField(
            model_name='customer',
            name='startdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, help_text='e.g Douala', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs_settings.cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Immediate Payment', 'Immediate Payment'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), ('2 Months', '2 Months'), ('End of Following Month', 'End of Following Month')], max_length=100, null=True, verbose_name='Customer Type'),
        ),
    ]
