# Generated by Django 4.2.3 on 2023-07-16 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import transfers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_location', '0001_initial'),
        ('product', '0003_alter_product_reorder_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Date of Purchase')),
                ('invoice_id', models.CharField(blank=True, default=transfers.models.increment_invoice_number, help_text='Auto Generated', max_length=500, null=True, verbose_name='Purchase Invoice Id')),
                ('sender', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Sender')),
                ('reciever', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Reciever')),
                ('storage_location', models.ForeignKey(blank=True, help_text='e.g WareHouse Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_location.storage', verbose_name='WareHouse')),
            ],
            options={
                'verbose_name': 'Transfer Transaction',
                'verbose_name_plural': 'Transfer Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Quantity')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('total_at_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
                ('transfer_trans_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfers.transfertransaction', verbose_name='Purchase Invoice Id')),
            ],
            options={
                'verbose_name': 'Transfer Details',
                'verbose_name_plural': 'Transfer Details',
            },
        ),
    ]
