# Generated by Django 4.2.3 on 2023-07-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertransaction',
            old_name='invoice_id',
            new_name='transfer_id',
        ),
        migrations.AddField(
            model_name='transfertransaction',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Transfer Outward', 'Transfer Outward'), ('Transfer Inward', 'Transfer Inward')], help_text='Transfer Outwards/Inwards', max_length=100, null=True, verbose_name='Transfer Type'),
        ),
    ]
