# Generated by Django 4.2.3 on 2023-07-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_location', '0001_initial'),
        ('transfers', '0002_rename_invoice_id_transfertransaction_transfer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferTransaction',
            new_name='TransferInvoice',
        ),
        migrations.AlterModelOptions(
            name='transferinvoice',
            options={'verbose_name': 'Transfer Invoice', 'verbose_name_plural': 'Transfer Invoices'},
        ),
        migrations.RenameField(
            model_name='transferdetail',
            old_name='transfer_trans_id',
            new_name='transfer_invoice_id',
        ),
    ]
