# Generated by Django 4.2.3 on 2023-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_rename_transfertransaction_transferinvoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferinvoice',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('Transfer Outwards', 'Transfer Outwards'), ('Transfer Inwards', 'Transfer Inwards')], help_text='Transfer Outwards/Inwards', max_length=100, null=True, verbose_name='Transfer Type'),
        ),
    ]
