"""
Django settings for stringent_erp_v1 project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f&@*1_hrr@(o9%z=zash9qr+v_feglm(2jx-midosl@_v#45fs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Customer Apps
    'configs_settings.apps.ConfigsSettingsConfig',
    'human_resource.apps.HumanResourceConfig',
    'inventory_management.apps.InventoryManagementConfig',
    'product.apps.ProductConfig',
    'storage_location.apps.StorageLocationConfig',
    'purchase.apps.PurchaseConfig',
    'transfers.apps.TransfersConfig',
    'customers.apps.CustomersConfig',
    'sales.apps.SalesConfig',
    'returns.apps.ReturnsConfig',
    'payments.apps.PaymentsConfig',



    # Third Party Apps
    'import_export',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stringent_erp_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stringent_erp_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'stringent', # database name
        'USER': 'root', #username
        'PASSWORD': 'root', #password
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



    #############   #############   #############   #############   #############
    #------------------------- JAZZMIN SETTINGS --------------------------------#
    #############   #############   #############   #############   #############
JAZZMIN_SETTINGS = {
    "site_title": "BJ COMPLEX",
    "site_header": "BJ COMPLEX",
    "site_brand": "BJ COMPLEX",
    "site_icon": "images/favicon.png",
    # Add your own branding here
    "site_logo": None,
    "welcome_sign": "Welcome to BJ COMPLEX LTD",
    # Copyright on the footer
    "copyright": "BJ COMPLEX",
    "user_avatar": None,

    "search_model": ["auth.User", "auth.Group", ],
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "BJ COMPLEX", "url": "home", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['returns'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        

        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",

         # Configs_settings
        "configs_settings.Region": "fas fa-globe-europe",
        "configs_settings.Country": "fas fa-flag",
        "configs_settings.Cities": "fas fa-city",
        "configs_settings.BranchManager": "fas fa-user",
        "configs_settings.WorkLocation": "fas fa-building",
        "configs_settings.Department": "fas fa-laptop-house",
        "configs_settings.SubDepartment": "fas fa-network-wired",
        "configs_settings.JobPosition": "fas fa-user-tie",

        # Customers
        "customers.Customer": "fas fa-users",

        # Human Resource
        "human_resource.Employee": "fas fa-users",

        # Sales
        "sales.SalesInvoices": "fas fa-file-invoice",
        "sales.SalesInvoiceDetail": "fas fa-shopping-cart",

        # Purchases
        "purchase.Vendor": "fas fa-users",
        "purchase.PurchaseInvoices": "fas fa-receipt",
        "purchase.PurchaseInvoicesDetail": "fas fa-shopping-basket",

        # Inventory Management
        "inventory_management.Inventory": "fas fa-boxes",
        "inventory_management.InventoryItems": "fas fa-pallet",

        # Product
        "product.Product": "fas fa-cubes",
        "product.ProductCategory": "fas fa-layer-group",

        # Storage
        "storage_location.Storage": "fas fa-warehouse",

        # Transfers
        "transfers.TransferInvoice": "fas fa-truck",
        "transfers.TransferDetail": "fas fa-file-alt",
    },
    # # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    # Uncomment this line once you create the bootstrap-dark.css file
    # "custom_css": "css/bootstrap-dark.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",

         "customers.Customer": "horizontal_tabs",
    },

    # Add a language dropdown into the admin
    "language_chooser": False,
}

    #############   #############   #############   #############   #############
    #------------------------- JAZZMIN UI TWEAKS SETTINGS --------------------------------#
    #############   #############   #############   #############   #############

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-info",
    "accent": "accent-info",
    "navbar": "navbar-info navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-light-info",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "pulse",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}