# Generated by Django 4.2.3 on 2023-07-17 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_reorder_level'),
        ('customers', '0005_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced_date', models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Invoiced Date')),
                ('department', models.DateField(default=django.utils.timezone.now, help_text='e.g 2023-07-01', verbose_name='Invoiced Date')),
                ('invoice_id', models.CharField(blank=True, default=sales.models.increment_invoice_number, help_text='Auto Generated', max_length=500, null=True, verbose_name='Purchase Invoice Id')),
                ('sales_person', models.CharField(default='', help_text='e.g Agbor Charles', max_length=200, verbose_name='Employee')),
                ('due_date', models.DateField(blank=True, help_text='e.g 2023-07-01', null=True, verbose_name='Due Date')),
                ('customer', models.ForeignKey(blank=True, help_text='e.g Meno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Quantity')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('vat', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Cost Price')),
                ('total_at_cost', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Amount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoices', verbose_name='Purchase Invoice Id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sales Invoice Items',
                'verbose_name_plural': 'Sales Invoice Items',
            },
        ),
    ]
