# Generated by Django 4.2.3 on 2023-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoicedetail',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Vat'),
        ),
        migrations.AlterField(
            model_name='salesinvoices',
            name='department',
            field=models.CharField(default='', help_text='e.g Agbor Charles', max_length=200, verbose_name='Branch'),
        ),
    ]
