# Generated by Django 4.2.3 on 2023-07-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesinvoicedetail_vat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoices',
            old_name='department',
            new_name='branch',
        ),
    ]
