# Generated by Django 4.2.3 on 2023-07-17 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_department_salesinvoices_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoices',
            name='branch',
        ),
    ]
