# Generated by Django 4.2.3 on 2023-07-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesinvoices_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoicedetail',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='salesinvoices',
            name='sales_person',
            field=models.CharField(default='', help_text='e.g Agbor Charles', max_length=200, verbose_name='Sales Person'),
        ),
    ]
