# Generated by Django 4.2.3 on 2023-07-19 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_location', '0001_initial'),
        ('sales', '0007_salesinvoices_distribution_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoices',
            name='distribution_point',
            field=models.ForeignKey(blank=True, help_text='e.g DS AKWA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_location.storage', verbose_name='Distribution Points'),
        ),
    ]
