# Generated by Django 4.2.3 on 2023-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salesinvoices_distribution_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoices',
            name='status',
            field=models.CharField(blank=True, default=(('Sales', 'Sales'), ('Returns', 'Returns')), help_text='Sales / Returns', max_length=500, null=True, verbose_name='Transaction Status'),
        ),
    ]
